imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@JcJolieCarBundle/Resources/config/services.yml" }

sensio_framework_extra:
    router:   { annotations: true }
    request:  { converters: true, auto_convert: true }
    view:     { annotations: true }
    cache:    { annotations: true }
    security: { annotations: true }
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            true
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'fields.html.twig'
    

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ JcJolieCarBundle, JcUserBundle, FOSUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        #yui_js:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Jc\UserBundle\Entity\User
    registration:
        form:
            type: jc_user_registration
fos_js_routing:
    routes_to_expose: ['jc_search']
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        jc:
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_french_analyzer:
                                type: custom
                                tokenizer: letter
                                filter: ["asciifolding", "lowercase", "french_stem", "stop_fr"]
                        filter:
                            stop_fr:
                                type: "stop"
                                stopwords: ["l","m","n","j","qu","n","s","d"]
            client: default
            types:
                Marque:
                    mappings: ~
                    persistence:
                        driver: orm
                        model:  Jc\JolieCarBundle\Entity\Marque
                        provider: ~
                        finder: ~
                Modele:
                    mappings: ~
                    persistence:
                        driver: orm
                        model:  Jc\JolieCarBundle\Entity\Modele
                        provider: ~
                        finder: ~
                Voiture:
                    mappings:
                        prix: ~
                        kmParcouru: ~
                        dateAcquisition: ~
                    persistence:
                        driver: orm
                        model:  Jc\JolieCarBundle\Entity\Voiture
                        provider: ~
                        finder: ~



#jms_di_extra:
#    locations:
#        all_bundles: false
#        bundles: [JolieCarBundle, UserBundle]
#        directories: ["%kernel.root_dir%/../src"]
#genemu_form:
#    select2:
#        enabled: true
#        configs:
#            placeholder: selectionner
#            allowClear: true

