fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#jc_user:
#    resource: "@JcUserBundle/Resources/config/routing.yml"
#    prefix:   /
#
jolieCar:
    resource: "@JcJolieCarBundle/Controller/"
    prefix:   /joliecar
    type: annotation

user:
    resource: "@JcUserBundle/Controller/"
    prefix:   /
    type: annotation


