<?php

namespace Jc\JolieCarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoitierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoitierRepository extends EntityRepository
{
    public function getHasard()
    {
        $boitiers = $this->findAll();
        $max = count($boitiers);
        return $boitiers[rand(1, $max)];
    }
}
