<?php

namespace Jc\JolieCarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends EntityRepository
{
    
    public function getModele()
    {
        $q = $this->createQueryBuilder('m')
                ->leftJoin('m.modeles', 'modele')
                ->getQuery();
        return $q->getArrayResult();
    }
}
