<?php

namespace Jc\JolieCarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcRepository extends EntityRepository
{
      public function getHasard()
    {
        $parc = $this->findAll();
        $max = count($parc);
        return $parc[rand(1, $max)];
    }
}
