<?php

namespace Jc\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeUserRepository extends EntityRepository
{
    public function findAllArray(){
        $q = $this->createQueryBuilder('ty')
            ->getQuery();

        return $q->getArrayResult();
    }
}
