parameters:
#    jc_user.example.class: Jc\UserBundle\Example

services:
#    jc_user.example:
#        class: %jc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    jc_user.registration.form.type:
        class: Jc\UserBundle\Form\UserType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: jc_user_registration}

    jc_user.loginsucceshandle:
        class: Jc\UserBundle\Model\LoginSuccessHandler
        arguments:  [ @router, @session]

    jc_user.logoutsucceshandle:
        class: Jc\UserBundle\Model\LogoutSuccessHandler
        arguments:  [ @router, @session]
